[project]
profile = format

[format]
image = alpine:latest

[alias:add-shfmt]
desc = Install shfmt.
cmd = apk add shfmt
hidden = true

[alias:ex-shfmt]
desc = Run shfmt.
cmd = shfmt -w -i 4 -ln bash -ci -kp dex
hidden = true

[alias:fmt]
desc = Format all shell scripts.
pipeline = add-shfmt,ex-shfmt
