[project]
profile = "rust"

[rust]
image = "rust:latest"
setup = "rustup component add rustfmt && rustup component add clippy && rustup target add x86_64-unknown-linux-musl && apt update && apt install --no-install-recommends -y gdb && apt clean && git config --global --add safe.directory /workspace"

[rust.fmt]
desc = "Run cargo fmt."
cmd = "cargo fmt"

[rust.clippy]
desc = "Run cargo clippy."
cmd = "cargo clippy --fix --allow-dirty"

[rust.release]
desc = "Run cargo release build."
cmd = "cargo build --release"

[rust.debug]
desc = "Run cargo debug build."
cmd = "cargo build"

[rust.run-gdb]
desc = "Run debug session."
cmd = "rust-gdb ./target/x86_64-unknown-linux-musl/debug/shrike"
interactive = true
hidden = true

[rust.gdb]
desc = "Run debug session."
pipeline = ["debug", "run-gdb"]

[rust.run]
desc = "Run binary"
cmd = "cargo run"
